server:
  port: ${{SERVER_PORT}:9015}
  servlet-path: /

ribbon:
  eureka:
    enabled: true
#eureka.client.register-with-eureka: false

eureka:
  validateInstanceId: false
  client:
    serviceUrl:
      defaultZone: http://10.111.24.224:9000/eureka/,http://10.111.24.234:9000/eureka/